### ISSUE TITLE
Bare Metal Inventory heading is missing

### ISSUE THREAD

**Issue by andybraren** [openshift-assisted/assisted-ui-lib#298]
The `Bare Metal Inventory` heading seems to have disappeared recently.

### Expected (old screenshot)

![image](https://user-images.githubusercontent.com/9122899/98773257-8f4adc00-23b6-11eb-949c-e55d558f1265.png)

### Current (in prod)

![image](https://user-images.githubusercontent.com/9122899/98773174-5e6aa700-23b6-11eb-8fd6-e6fa2a11d146.png)

**Comment by jkilzi** [comment]
[Bug 1914891](https://bugzilla.redhat.com/show_bug.cgi?id=1914891)

**Comment by jkilzi** [comment]
Closing as won't fix for now since we'll have a different set of requirements for the wizard. Please feel free to reopen or link to this issue in the future if necessary.
